zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null
  ignore_path: null

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE,https://api.deepseek.com}
  api_mode: chat_completion
  generation_kwargs:
    model: deepseek-flash
    max_tokens: 16384

source:
  arxiv:
    category: ["cs.PL", "cs.AR", "cs.DC", "cs.ET", "cs.PF", "cs.OS", "cs.LO", "cs.SE", "cs.AI", "cs.LG", "eess.SP"]
    include_cross_list: true

executor:
  debug: ${oc.env:DEBUG,null}
  max_paper_num: 10
  source: ["arxiv"]
